In [1]:
import sys
sys.path.append('../')

import pandas as pd
from functools import partial
from util.polymarket_client import PolymarketAPIClient
from trading_rules import entries as e, exits as ex, engine
from trading_rules.metrics import Metrics
from util.data_processor import TickDataIntervalEnum

In [2]:
# FETCH THE DATA STEP AND PROCESS IT
MARKET_SLUG = 'will-jesus-christ-return-in-2025'
client = PolymarketAPIClient()
market = client.get_price_history_by_outcome(MARKET_SLUG, desired_outcome="No", interval=TickDataIntervalEnum.FIVE_MINUTES)
market["symbol"] = MARKET_SLUG
resampled_df = market.resample("10min").last()

Will Jesus Christ return in 2025?
Not Will Jesus Christ return in 2025?
requested start and end: 2024-12-31 12:00:00+00:00 2025-12-31 12:00:00+00:00

In [3]:
resampled_df

,timestamp,open,high,low,close,volume,outcome_id,symbol
timestamp_formatted,,,,,,,,
2025-03-20 22:10:00+00:00,1.742509e+12,0.9700,0.9700,0.9700,0.9700,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-03-20 22:20:00+00:00,1.742510e+12,0.9695,0.9695,0.9695,0.9695,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-03-20 22:30:00+00:00,1.742510e+12,0.9650,0.9650,0.9650,0.9650,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-03-20 22:40:00+00:00,1.742511e+12,0.9670,0.9670,0.9670,0.9670,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-03-20 22:50:00+00:00,1.742511e+12,0.9610,0.9610,0.9610,0.9610,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
...,...,...,...,...,...,...,...,...
2025-12-31 11:10:00+00:00,1.767180e+12,0.9995,0.9995,0.9995,0.9995,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-12-31 11:20:00+00:00,1.767180e+12,0.9995,0.9995,0.9995,0.9995,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-12-31 11:30:00+00:00,1.767181e+12,0.9995,0.9995,0.9995,0.9995,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-12-31 11:40:00+00:00,1.767182e+12,0.9995,0.9995,0.9995,0.9995,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025
2025-12-31 11:50:00+00:00,1.767182e+12,0.9995,0.9995,0.9995,0.9995,0.0,4334699957357127908482970555095165722856012218...,will-jesus-christ-return-in-2025

In [4]:
# RUN THE SIMULATED BACKTEST

entries_partials = [
    partial(e.mean_reversion, data=resampled_df, window=10)
]
entries_series = [entry(data=resampled_df) for entry in entries_partials]
# AND all the entry rules
entries = pd.concat(entries_series, axis=1).all(axis=1)
exit_rules = [ex.time_exit(max_bars=144)]

result = engine.backtest(
    data=resampled_df,
    entries_series=entries,
    exits_list=exit_rules,
    initial_cash=10000,
)

result

{'equity': timestamp_formatted
 2025-03-20 22:10:00+00:00    10000.000000
 2025-03-20 22:20:00+00:00    10000.000000
 2025-03-20 22:30:00+00:00    10000.000000
 2025-03-20 22:40:00+00:00    10000.000000
 2025-03-20 22:50:00+00:00    10000.000000
                                  ...
 2025-12-31 11:10:00+00:00    10881.900953
 2025-12-31 11:20:00+00:00    10881.900953
 2025-12-31 11:30:00+00:00    10881.900953
 2025-12-31 11:40:00+00:00    10881.900953
 2025-12-31 11:50:00+00:00    10881.900953
 Freq: 10min, Length: 41123, dtype: float64,
 'trades': [{'entry_price': 0.9625,
   'qty': 10389.610389610389,
   'entry_idx': 9,
   'exit_price': 0.971,
   'exit_idx': 153},
  {'entry_price': 0.971,
   'qty': 10389.610389610389,
   'entry_idx': 157,
   'exit_price': 0.9685,
   'exit_idx': 301},
  {'entry_price': 0.9685,
   'qty': 10389.610389610389,
   'entry_idx': 302,
   'exit_price': 0.969,
   'exit_idx': 446},
  {'entry_price': 0.9685,
   'qty': 10394.974153363413,
   'entry_idx': 459,
   'exit_price': 0.967,
   'exit_idx': 603},
  {'entry_price': 0.9665,
   'qty': 10400.35179131135,
   'entry_idx': 604,
   'exit_price': 0.9715,
   'exit_idx': 748},
  {'entry_price': 0.971,
   'qty': 10405.70727627083,
   'entry_idx': 750,
   'exit_price': 0.971,
   'exit_idx': 894},
  {'entry_price': 0.971,
   'qty': 10405.70727627083,
   'entry_idx': 904,
   'exit_price': 0.97,
   'exit_idx': 1048},
  {'entry_price': 0.97,
   'qty': 10405.70727627083,
   'entry_idx': 1049,
   'exit_price': 0.97,
   'exit_idx': 1193},
  {'entry_price': 0.9695,
   'qty': 10411.07380916215,
   'entry_idx': 1227,
   'exit_price': 0.969,
   'exit_idx': 1371},
  {'entry_price': 0.9715,
   'qty': 10384.282574449946,
   'entry_idx': 1653,
   'exit_price': 0.971,
   'exit_idx': 1797},
  {'entry_price': 0.9705,
   'qty': 10389.632539712413,
   'entry_idx': 1835,
   'exit_price': 0.97,
   'exit_idx': 1979},
  {'entry_price': 0.97,
   'qty': 10389.632539712413,
   'entry_idx': 1980,
   'exit_price': 0.971,
   'exit_idx': 2124},
  {'entry_price': 0.9695,
   'qty': 10405.707267726408,
   'entry_idx': 2151,
   'exit_price': 0.9725,
   'exit_idx': 2295},
  {'entry_price': 0.972,
   'qty': 10411.0599978024,
   'entry_idx': 2398,
   'exit_price': 0.971,
   'exit_idx': 2542},
  {'entry_price': 0.9705,
   'qty': 10416.423758749233,
   'entry_idx': 2617,
   'exit_price': 0.9675,
   'exit_idx': 2761},
  {'entry_price': 0.9685,
   'qty': 10405.668545782017,
   'entry_idx': 2848,
   'exit_price': 0.969,
   'exit_idx': 2992},
  {'entry_price': 0.969,
   'qty': 10405.668545782017,
   'entry_idx': 3053,
   'exit_price': 0.9705,
   'exit_idx': 3197},
  {'entry_price': 0.968,
   'qty': 10432.542689753562,
   'entry_idx': 3327,
   'exit_price': 0.968,
   'exit_idx': 3471},
  {'entry_price': 0.9675,
   'qty': 10437.934184683667,
   'entry_idx': 3537,
   'exit_price': 0.9685,
   'exit_idx': 3681},
  {'entry_price': 0.9675,
   'qty': 10448.722747148457,
   'entry_idx': 3717,
   'exit_price': 0.967,
   'exit_idx': 3861},
  {'entry_price': 0.966,
   'qty': 10459.539230323559,
   'entry_idx': 3869,
   'exit_price': 0.969,
   'exit_idx': 4013},
  {'entry_price': 0.968,
   'qty': 10470.344539445794,
   'entry_idx': 4028,
   'exit_price': 0.9685,
   'exit_idx': 4172},
  {'entry_price': 0.9685,
   'qty': 10470.344539445794,
   'entry_idx': 4182,
   'exit_price': 0.9645,
   'exit_idx': 4326},
  {'entry_price': 0.965,
   'qty': 10464.919490461627,
   'entry_idx': 4379,
   'exit_price': 0.97,
   'exit_idx': 4523},
  {'entry_price': 0.97,
   'qty': 10464.919490461627,
   'entry_idx': 4542,
   'exit_price': 0.964,
   'exit_idx': 4686},
  {'entry_price': 0.964,
   'qty': 10464.919490461627,
   'entry_idx': 4688,
   'exit_price': 0.9675,
   'exit_idx': 4832},
  {'entry_price': 0.9645,
   'qty': 10497.46978436664,
   'entry_idx': 4833,
   'exit_price': 0.9645,
   'exit_idx': 4977},
  {'entry_price': 0.9655,
   'qty': 10486.597210794018,
   'entry_idx': 5109,
   'exit_price': 0.9655,
   'exit_idx': 5253},
  {'entry_price': 0.9695,
   'qty': 10443.331208892858,
   'entry_idx': 5313,
   'exit_price': 0.9745,
   'exit_idx': 5457},
  {'entry_price': 0.9735,
   'qty': 10454.058821844983,
   'entry_idx': 5459,
   'exit_price': 0.9715,
   'exit_idx': 5603},
  {'entry_price': 0.97,
   'qty': 10470.224892188042,
   'entry_idx': 5670,
   'exit_price': 0.972,
   'exit_idx': 5814},
  {'entry_price': 0.9705,
   'qty': 10486.407619996677,
   'entry_idx': 5849,
   'exit_price': 0.9705,
   'exit_idx': 5993},
  {'entry_price': 0.9705,
   'qty': 10486.407619996677,
   'entry_idx': 6006,
   'exit_price': 0.9755,
   'exit_idx': 6150},
  {'entry_price': 0.973,
   'qty': 10513.351113367688,
   'entry_idx': 6159,
   'exit_price': 0.9735,
   'exit_idx': 6303},
  {'entry_price': 0.9715,
   'qty': 10534.994656575855,
   'entry_idx': 6334,
   'exit_price': 0.971,
   'exit_idx': 6478},
  {'entry_price': 0.9725,
   'qty': 10518.745307491161,
   'entry_idx': 6632,
   'exit_price': 0.9735,
   'exit_idx': 6776},
  {'entry_price': 0.9725,
   'qty': 10529.561498038709,
   'entry_idx': 6809,
   'exit_price': 0.9695,
   'exit_idx': 6953},
  {'entry_price': 0.9705,
   'qty': 10518.711872589933,
   'entry_idx': 6996,
   'exit_price': 0.97,
   'exit_idx': 7140},
  {'entry_price': 0.97,
   'qty': 10518.711872589933,
   'entry_idx': 7155,
   'exit_price': 0.97,
   'exit_idx': 7299},
  {'entry_price': 0.97,
   'qty': 10518.711872589933,
   'entry_idx': 7343,
   'exit_price': 0.9705,
   'exit_idx': 7487},
  {'entry_price': 0.9705,
   'qty': 10518.711872589933,
   'entry_idx': 7512,
   'exit_price': 0.9705,
   'exit_idx': 7656},
  {'entry_price': 0.9705,
   'qty': 10518.711872589933,
   'entry_idx': 7692,
   'exit_price': 0.9705,
   'exit_idx': 7836},
  {'entry_price': 0.9695,
   'qty': 10529.561498038709,
   'entry_idx': 7883,
   'exit_price': 0.969,
   'exit_idx': 8027},
  {'entry_price': 0.9685,
   'qty': 10534.997513267432,
   'entry_idx': 8109,
   'exit_price': 0.968,
   'exit_idx': 8253},
  {'entry_price': 0.968,
   'qty': 10534.997513267432,
   'entry_idx': 8312,
   'exit_price': 0.968,
   'exit_idx': 8456},
  {'entry_price': 0.9675,
   'qty': 10540.441956426743,
   'entry_idx': 8494,
   'exit_price': 0.9675,
   'exit_idx': 8638},
  {'entry_price': 0.9675,
   'qty': 10540.441956426743,
   'entry_idx': 8654,
   'exit_price': 0.97,
   'exit_idx': 8798},
  {'entry_price': 0.97,
   'qty': 10540.441956426743,
   'entry_idx': 8799,
   'exit_price': 0.9705,
   'exit_idx': 8943},
  {'entry_price': 0.971,
   'qty': 10535.014334410045,
   'entry_idx': 9101,
   'exit_price': 0.971,
   'exit_idx': 9245},
  {'entry_price': 0.971,
   'qty': 10535.014334410045,
   'entry_idx': 9312,
   'exit_price': 0.9715,
   'exit_idx': 9456},
  {'entry_price': 0.9715,
   'qty': 10535.014334410045,
   'entry_idx': 9472,
   'exit_price': 0.9665,
   'exit_idx': 9616},
  {'entry_price': 0.966,
   'qty': 10540.467240380236,
   'entry_idx': 9633,
   'exit_price': 0.9675,
   'exit_idx': 9777},
  {'entry_price': 0.968,
   'qty': 10535.02278416103,
   'entry_idx': 9841,
   'exit_price': 0.9685,
   'exit_idx': 9985},
  {'entry_price': 0.968,
   'qty': 10540.464428161113,
   'entry_idx': 10015,
   'exit_price': 0.9705,
   'exit_idx': 10159},
  {'entry_price': 0.9705,
   'qty': 10540.464428161113,
   'entry_idx': 10535,
   'exit_price': 0.972,
   'exit_idx': 10679},
  {'entry_price': 0.9715,
   'qty': 10545.889268319714,
   'entry_idx': 10849,
   'exit_price': 0.971,
   'exit_idx': 10993},
  {'entry_price': 0.973,
   'qty': 10524.212209186477,
   'entry_idx': 11112,
   'exit_price': 0.9715,
   'exit_idx': 11256},
  {'entry_price': 0.9715,
   'qty': 10524.212209186477,
   'entry_idx': 11447,
   'exit_price': 0.972,
   'exit_idx': 11591},
  {'entry_price': 0.9715,
   'qty': 10529.628684847405,
   'entry_idx': 11627,
   'exit_price': 0.9725,
   'exit_idx': 11771},
  {'entry_price': 0.9715,
   'qty': 10540.467211543079,
   'entry_idx': 11792,
   'exit_price': 0.972,
   'exit_idx': 11936},
  {'entry_price': 0.9715,
   'qty': 10545.892053134197,
   'entry_idx': 11977,
   'exit_price': 0.9715,
   'exit_idx': 12121},
  {'entry_price': 0.9715,
   'qty': 10545.892053134197,
   'entry_idx': 12147,
   'exit_price': 0.9715,
   'exit_idx': 12291},
  {'entry_price': 0.971,
   'qty': 10551.322481585863,
   'entry_idx': 12299,
   'exit_price': 0.972,
   'exit_idx': 12443},
  {'entry_price': 0.973,
   'qty': 10540.478368038497,
   'entry_idx': 13098,
   'exit_price': 0.974,
   'exit_idx': 13242},
  {'entry_price': 0.9735,
   'qty': 10545.892070333328,
   'entry_idx': 13297,
   'exit_price': 0.973,
   'exit_idx': 13441},
  {'entry_price': 0.9725,
   'qty': 10551.314122811647,
   'entry_idx': 13498,
   'exit_price': 0.973,
   'exit_idx': 13642},
  {'entry_price': 0.9725,
   'qty': 10556.738962977617,
   'entry_idx': 13646,
   'exit_price': 0.973,
   'exit_idx': 13790},
  {'entry_price': 0.9725,
   'qty': 10562.166592264495,
   'entry_idx': 13793,
   'exit_price': 0.9735,
   'exit_idx': 13937},
  {'entry_price': 0.973,
   'qty': 10567.594221551373,
   'entry_idx': 13942,
   'exit_price': 0.973,
   'exit_idx': 14086},
  {'entry_price': 0.973,
   'qty': 10567.594221551373,
   'entry_idx': 14169,
   'exit_price': 0.973,
   'exit_idx': 14313},
  {'entry_price': 0.973,
   'qty': 10567.594221551373,
   'entry_idx': 14427,
   'exit_price': 0.9735,
   'exit_idx': 14571},
  {'entry_price': 0.9725,
   'qty': 10578.460642344742,
   'entry_idx': 14631,
   'exit_price': 0.9755,
   'exit_idx': 14775},
  {'entry_price': 0.977,
   'qty': 10562.219402873385,
   'entry_idx': 15120,
   'exit_price': 0.9765,
   'exit_idx': 15264},
  {'entry_price': 0.9765,
   'qty': 10562.219402873385,
   'entry_idx': 15383,
   'exit_price': 0.9775,
   'exit_idx': 15527},
  {'entry_price': 0.977,
   'qty': 10567.624837572912,
   'entry_idx': 15579,
   'exit_price': 0.977,
   'exit_idx': 15723},
  {'entry_price': 0.9765,
   'qty': 10573.035807791843,
   'entry_idx': 15777,
   'exit_price': 0.9765,
   'exit_idx': 15921},
  {'entry_price': 0.9765,
   'qty': 10573.035807791843,
   'entry_idx': 15922,
   'exit_price': 0.9765,
   'exit_idx': 16066},
  {'entry_price': 0.9755,
   'qty': 10583.874388835196,
   'entry_idx': 16087,
   'exit_price': 0.9755,
   'exit_idx': 16231},
  {'entry_price': 0.9755,
   'qty': 10583.874388835196,
   'entry_idx': 16365,
   'exit_price': 0.9765,
   'exit_idx': 16509},
  {'entry_price': 0.976,
   'qty': 10589.296455632757,
   'entry_idx': 16626,
   'exit_price': 0.9765,
   'exit_idx': 16770},
  {'entry_price': 0.9765,
   'qty': 10589.296455632757,
   'entry_idx': 16821,
   'exit_price': 0.9775,
   'exit_idx': 16965},
  {'entry_price': 0.977,
   'qty': 10594.715747575252,
   'entry_idx': 16979,
   'exit_price': 0.978,
   'exit_idx': 17123},
  {'entry_price': 0.9775,
   'qty': 10600.135039517745,
   'entry_idx': 17126,
   'exit_price': 0.9775,
   'exit_idx': 17270},
  {'entry_price': 0.977,
   'qty': 10605.559878330192,
   'entry_idx': 17340,
   'exit_price': 0.977,
   'exit_idx': 17484},
  {'entry_price': 0.977,
   'qty': 10605.559878330192,
   'entry_idx': 17887,
   'exit_price': 0.977,
   'exit_idx': 18031},
  {'entry_price': 0.977,
   'qty': 10605.559878330192,
   'entry_idx': 18032,
   'exit_price': 0.977,
   'exit_idx': 18176},
  {'entry_price': 0.9765,
   'qty': 10610.990272533125,
   'entry_idx': 18200,
   'exit_price': 0.9765,
   'exit_idx': 18344},
  {'entry_price': 0.977,
   'qty': 10605.559878330192,
   'entry_idx': 18407,
   'exit_price': 0.9765,
   'exit_idx': 18551},
  {'entry_price': 0.9765,
   'qty': 10605.559878330192,
   'entry_idx': 18579,
   'exit_price': 0.9755,
   'exit_idx': 18723},
  {'entry_price': 0.976,
   'qty': 10600.126702163016,
   'entry_idx': 19020,
   'exit_price': 0.976,
   'exit_idx': 19164},
  {'entry_price': 0.9755,
   'qty': 10605.559878330192,
   'entry_idx': 19266,
   'exit_price': 0.9775,
   'exit_idx': 19410},
  {'entry_price': 0.9775,
   'qty': 10605.559878330192,
   'entry_idx': 19448,
   'exit_price': 0.9765,
   'exit_idx': 19592},
  {'entry_price': 0.9765,
   'qty': 10605.559878330192,
   'entry_idx': 19847,
   'exit_price': 0.9765,
   'exit_idx': 19991},
  {'entry_price': 0.977,
   'qty': 10600.132263244046,
   'entry_idx': 20088,
   'exit_price': 0.977,
   'exit_idx': 20232},
  {'entry_price': 0.9775,
   'qty': 10594.710200705302,
   'entry_idx': 20334,
   'exit_price': 0.9775,
   'exit_idx': 20478},
  {'entry_price': 0.978,
   'qty': 10589.293682197786,
   'entry_idx': 20516,
   'exit_price': 0.978,
   'exit_idx': 20660},
  {'entry_price': 0.978,
   'qty': 10589.293682197786,
   'entry_idx': 20669,
   'exit_price': 0.9795,
   'exit_idx': 20813},
  {'entry_price': 0.9795,
   'qty': 10589.293682197786,
   'entry_idx': 20814,
   'exit_price': 0.9795,
   'exit_idx': 20958},
  {'entry_price': 0.9795,
   'qty': 10589.293682197786,
   'entry_idx': 20959,
   'exit_price': 0.981,
   'exit_idx': 21103},
  {'entry_price': 0.981,
   'qty': 10589.293682197786,
   'entry_idx': 21107,
   'exit_price': 0.9815,
   'exit_idx': 21251},
  {'entry_price': 0.981,
   'qty': 10594.690875715727,
   'entry_idx': 21253,
   'exit_price': 0.983,
   'exit_idx': 21397},
  {'entry_price': 0.983,
   'qty': 10594.690875715727,
   'entry_idx': 21401,
   'exit_price': 0.9825,
   'exit_idx': 21545},
  {'entry_price': 0.9825,
   'qty': 10594.690875715727,
   'entry_idx': 21837,
   'exit_price': 0.9825,
   'exit_idx': 21981},
  {'entry_price': 0.984,
   'qty': 10578.540432307624,
   'entry_idx': 22580,
   'exit_price': 0.984,
   'exit_idx': 22724},
  {'entry_price': 0.984,
   'qty': 10578.540432307624,
   'entry_idx': 22885,
   'exit_price': 0.984,
   'exit_idx': 23029},
  {'entry_price': 0.984,
   'qty': 10578.540432307624,
   'entry_idx': 23146,
   'exit_price': 0.984,
   'exit_idx': 23290},
  {'entry_price': 0.984,
   'qty': 10578.540432307624,
   'entry_idx': 23475,
   'exit_price': 0.9875,
   'exit_idx': 23619},
  {'entry_price': 0.988,
   'qty': 10573.186919943095,
   'entry_idx': 23702,
   'exit_price': 0.9885,
   'exit_idx': 23846},
  {'entry_price': 0.989,
   'qty': 10567.841527162538,
   'entry_idx': 23859,
   'exit_price': 0.9925,
   'exit_idx': 24003},
  {'entry_price': 0.9925,
   'qty': 10567.841527162538,
   'entry_idx': 24004,
   'exit_price': 0.991,
   'exit_idx': 24148},
  {'entry_price': 0.9905,
   'qty': 10573.176126620974,
   'entry_idx': 24191,
   'exit_price': 0.9885,
   'exit_idx': 24335},
  {'entry_price': 0.9885,
   'qty': 10573.176126620974,
   'entry_idx': 24526,
   'exit_price': 0.9885,
   'exit_idx': 24670},
  {'entry_price': 0.9865,
   'qty': 10594.611861292278,
   'entry_idx': 24704,
   'exit_price': 0.9885,
   'exit_idx': 24848},
  {'entry_price': 0.987,
   'qty': 10610.71309512403,
   'entry_idx': 24866,
   'exit_price': 0.9875,
   'exit_idx': 25010},
  {'entry_price': 0.987,
   'qty': 10616.088329721359,
   'entry_idx': 25012,
   'exit_price': 0.987,
   'exit_idx': 25156},
  {'entry_price': 0.9865,
   'qty': 10621.469013111993,
   'entry_idx': 25158,
   'exit_price': 0.987,
   'exit_idx': 25302},
  {'entry_price': 0.9865,
   'qty': 10626.852423660961,
   'entry_idx': 25303,
   'exit_price': 0.9855,
   'exit_idx': 25447},
  {'entry_price': 0.9855,
   'qty': 10626.852423660961,
   'entry_idx': 25451,
   'exit_price': 0.986,
   'exit_idx': 25595},
  {'entry_price': 0.986,
   'qty': 10626.852423660961,
   'entry_idx': 25607,
   'exit_price': 0.9855,
   'exit_idx': 25751},
  {'entry_price': 0.987,
   'qty': 10610.70219201406,
   'entry_idx': 25804,
   'exit_price': 0.986,
   'exit_idx': 25948},
  {'entry_price': 0.986,
   'qty': 10610.70219201406,
   'entry_idx': 25949,
   'exit_price': 0.987,
   'exit_idx': 26093},
  {'entry_price': 0.9865,
   'qty': 10616.080145481883,
   'entry_idx': 26186,
   'exit_price': 0.9875,
   'exit_idx': 26330},
  {'entry_price': 0.9865,
   'qty': 10626.841503966913,
   'entry_idx': 26425,
   'exit_price': 0.9865,
   'exit_idx': 26569},
  {'entry_price': 0.9865,
   'qty': 10626.841503966913,
   'entry_idx': 26636,
   'exit_price': 0.985,
   'exit_idx': 26780},
  {'entry_price': 0.985,
   'qty': 10626.841503966913,
   'entry_idx': 26781,
   'exit_price': 0.987,
   'exit_idx': 26925},
  {'entry_price': 0.987,
   'qty': 10626.841503966913,
   'entry_idx': 26926,
   'exit_price': 0.9885,
   'exit_idx': 27070},
  {'entry_price': 0.9895,
   'qty': 10616.10189658544,
   'entry_idx': 27072,
   'exit_price': 0.9895,
   'exit_idx': 27216},
  {'entry_price': 0.989,
   'qty': 10621.468985511925,
   'entry_idx': 27222,
   'exit_price': 0.9885,
   'exit_idx': 27366},
  {'entry_price': 0.99,
   'qty': 10605.375850685392,
   'entry_idx': 27385,
   'exit_price': 0.9895,
   'exit_idx': 27529},
  {'entry_price': 0.9895,
   'qty': 10605.375850685392,
   'entry_idx': 27654,
   'exit_price': 0.9895,
   'exit_idx': 27798},
  {'entry_price': 0.9875,
   'qty': 10626.85509291463,
   'entry_idx': 27802,
   'exit_price': 0.9875,
   'exit_idx': 27946},
  {'entry_price': 0.9885,
   'qty': 10616.104607236415,
   'entry_idx': 28021,
   'exit_price': 0.987,
   'exit_idx': 28165},
  {'entry_price': 0.9865,
   'qty': 10621.485298877184,
   'entry_idx': 28182,
   'exit_price': 0.987,
   'exit_idx': 28326},
  {'entry_price': 0.987,
   'qty': 10621.485298877184,
   'entry_idx': 28327,
   'exit_price': 0.989,
   'exit_idx': 28471},
  {'entry_price': 0.9885,
   'qty': 10626.857825583747,
   'entry_idx': 28497,
   'exit_price': 0.9885,
   'exit_idx': 28641},
  {'entry_price': 0.9885,
   'qty': 10626.857825583747,
   'entry_idx': 28642,
   'exit_price': 0.9895,
   'exit_idx': 28786},
  {'entry_price': 0.9875,
   'qty': 10648.380575610247,
   'entry_idx': 28916,
   'exit_price': 0.9865,
   'exit_idx': 29060},
  {'entry_price': 0.986,
   'qty': 10653.780362920394,
   'entry_idx': 29068,
   'exit_price': 0.988,
   'exit_idx': 29212},
  {'entry_price': 0.988,
   'qty': 10653.780362920394,
   'entry_idx': 29285,
   'exit_price': 0.986,
   'exit_idx': 29429},
  {'entry_price': 0.986,
   'qty': 10653.780362920394,
   'entry_idx': 29503,
   'exit_price': 0.9885,
   'exit_idx': 29647},
  {'entry_price': 0.9885,
   'qty': 10653.780362920394,
   'entry_idx': 29731,
   'exit_price': 0.9875,
   'exit_idx': 29875},
  {'entry_price': 0.9885,
   'qty': 10643.002638729275,
   'entry_idx': 29928,
   'exit_price': 0.9895,
   'exit_idx': 30072},
  {'entry_price': 0.99,
   'qty': 10637.62738487133,
   'entry_idx': 30094,
   'exit_price': 0.988,
   'exit_idx': 30238},
  {'entry_price': 0.989,
   'qty': 10626.871442116151,
   'entry_idx': 30298,
   'exit_price': 0.9905,
   'exit_idx': 30442},
  {'entry_price': 0.9905,
   'qty': 10626.871442116151,
   'entry_idx': 30443,
   'exit_price': 0.9885,
   'exit_idx': 30587},
  {'entry_price': 0.9895,
   'qty': 10616.131804478844,
   'entry_idx': 30642,
   'exit_price': 0.991,
   'exit_idx': 30786},
  {'entry_price': 0.9905,
   'qty': 10621.490780654754,
   'entry_idx': 30791,
   'exit_price': 0.9915,
   'exit_idx': 30935},
  {'entry_price': 0.991,
   'qty': 10626.849756830665,
   'entry_idx': 31057,
   'exit_price': 0.9905,
   'exit_idx': 31201},
  {'entry_price': 0.9905,
   'qty': 10626.849756830665,
   'entry_idx': 31202,
   'exit_price': 0.989,
   'exit_idx': 31346},
  {'entry_price': 0.989,
   'qty': 10626.849756830665,
   'entry_idx': 31355,
   'exit_price': 0.9895,
   'exit_idx': 31499},
  {'entry_price': 0.9895,
   'qty': 10626.849756830665,
   'entry_idx': 31674,
   'exit_price': 0.9905,
   'exit_idx': 31818},
  {'entry_price': 0.991,
   'qty': 10621.488076832266,
   'entry_idx': 32092,
   'exit_price': 0.9925,
   'exit_idx': 32236},
  {'entry_price': 0.9925,
   'qty': 10621.488076832266,
   'entry_idx': 32426,
   'exit_price': 0.9925,
   'exit_idx': 32570},
  {'entry_price': 0.992,
   'qty': 10626.841649451637,
   'entry_idx': 32576,
   'exit_price': 0.992,
   'exit_idx': 32720},
  {'entry_price': 0.9905,
   'qty': 10642.93479682587,
   'entry_idx': 32724,
   'exit_price': 0.9915,
   'exit_idx': 32868},
  {'entry_price': 0.9905,

In [6]:
# MEASURE PERFORMANCE USING METRICS
metrics = Metrics(result['trades'], result['equity'])
metrics.summary()

   Total Return       CAR    Sharpe  Max Drawdown  Trades
0       0.08819  0.114157  3.265826     -0.019659     189